# Generated by Django 4.0.4 on 2022-06-14 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_category_lead_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='organisation',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='organisation',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_organisor',
            new_name='is_organizor',
        ),
    ]
